#cloud-config

coreos:
    units:
      - name: ec2-ssh-key.service
        runtime: yes
        content: |
          [Unit]
          Description=Sets SSH key from metadata

          [Service]
          Type=oneshot
          StandardOutput=journal+console
          ExecStart=/usr/share/oem/usr/bin/ec2-ssh-key.sh
      - name: ec2-cloudinit.service
        runtime: yes
        content: |
          [Unit]
          Description=Cloudinit from EC2 metadata

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/coreos-cloudinit -from-url=http://169.254.169.254/latest/user-data
      - name: ec2-c10n.service
        runtime: yes
        content: |
          [Unit]
          Description=Legacy c10n support from EC2 metadata
          Requires=ec2-cloudinit.service
          After=ec2-cloudinit.service

          [Service]
          Type=oneshot
          RemainAfterExit=no
          ExecStart=/usr/share/oem/usr/bin/coreos-c10n
